apply-ng: Avoid more GroovyRuntimeExceptions
Avoids exception when --scm-url param is added.

java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$1158
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:54)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:141)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:101)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:93)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:78)
        at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3272)
        at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3264)
        at groovy.lang.MetaClassImpl.getNormalMethodWithCaching(MetaClassImpl.java:1460)
        at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1376)
        at groovy.lang.MetaClassImpl.getMetaMethod(MetaClassImpl.java:1280)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1132)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1017)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1008)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:603)
        at com.cloudogu.gitops.core.ApplicationConfigurator.setScmmConfig(ApplicationConfigurator.groovy:79)
        at com.cloudogu.gitops.core.ApplicationConfigurator.populateConfig(ApplicationConfigurator.groovy:34)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCli.run(GitopsPlaygroundCli.groovy:112)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
        at com.cloudogu.gitops.cli.GitopsPlaygroundCli.main(GitopsPlaygroundCli.groovy:103)