e2e.groovy: Run only non-folder jobs.
This is helpful when e2e.groovy is used on a jenkins instance that contains other jobs, not only the gitOps SCM Folders.

For non-folder jobs we would otherwise run into this exception:

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
...
at JenkinsHandler$_buildJobList_closure1.doCall(e2e.groovy:94)