Fix dev image
23fb76a1 actually starts to interpret groovy code. Before we unknowingly
 executed the bytecode (class files) from the jar.

So we never knew about this bug:
ArgoCdApplicationStrategy.groovy ran Path.text even though Path in
groovy does not have .text.
The compile somehow seems to make this right but the groovy interpreter
does not 🤷‍♂️

Exception was as follows:
 Deploying helm chart via ArgoCD: ingress-nginx. Reading values from /tmp/gitops-playground-7884415950616070308
11:24:14.741 [main] DEBUG com.cloudogu.gitops.scmm.ScmmRepo - Cloning argocd/cluster-resources repo
11:24:14.864 [main] DEBUG com.cloudogu.gitops.scmm.ScmmRepo - Checking out main for repo argocd/cluster-resources
groovy.lang.MissingPropertyException: No such property: text for class: sun.nio.fs.UnixPath
Possible solutions: root
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
        at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:161)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at com.cloudogu.gitops.features.deployment.ArgoCdApplicationStrategy.deployFeature(ArgoCdApplicationStrategy.groovy:42)