Facilitate first multi-arch build for ARM64
Pragmatically start with dev image only.
Prod image might be possible after we upgraded to new Graal Images.

Had to switch from temuri to zulu, because temurin alpine is amd64 only

Problems:
Image is not running on arm64
ghcr.io/cloudogu/gito
ps-playground:a0b877a-dev
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: /usr/lib/jvm/zulu17-ca/lib/server:/usr/lib/jvm/zulu17-ca/lib:/usr/lib/jvm/zulu17-ca/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, /tmp/libjansi-64-17571266802134536998.so: Error relocating /tmp/libjansi-64-17571266802134536998.so: unsupported relocation type 7 (Possible cause: can't load AMD 64 .so on a AARCH64 platform)]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
        at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at ch.qos.logback.core.ConsoleAppender.wrapWithJansi
(ConsoleAppender.java:114)
..
com.cloudogu.gitops.cli.GitopsPlaygroundCliMainScripted.<clinit>(GitopsPlaygroundCliMainScripted.groovy)

Latest commit can not be built because there are errors downloading
Jenkins plugin, only on arm64.
Tries to download from:
https://get.jenkins.io/plugins/font-awesome-api-plugin/6.6.0-2/font-awesome-api-plugin.hpi

causing 404, while amd64 loads succesfully from
https://updates.jenkins.io/download/plugins/font-awesome-api/6.6.0-2/font-awesome-api.hpi
🤷