Fix REGISTRY_URL not set when run without --debug.
Results in failing Jenkins builds. Errors, e.g.

-Dspring-boot.build-image.imageName=/spring-petclinic-plain:202104011633-8942587-main -V

org.eclipse.jgit.api.errors.TransportException: http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/petclinic-plain: Authentication is required but no CredentialsProvider has been registered

Unable to parse image reference "/spring-petclinic-plain:202104011633-8942587-main". Image reference must be in the form '[domainHost:port/][path/]name[:tag][@digest]', with 'path' and 'name' containing only [a-z0-9][.][_][-] -> [Help 1]