Remove static node port of Jenkins
Removing NetworkUtils from ApplicationConfigurator causes error in
GraalVM Native Build:
com.oracle.svm.core.util.VMError$HostedError: Registering type as reachable after analysis: AnalysisType<okhttp3.internal.http.RetryAndFollowUpInterceptor$Companion, allocated: 0, inHeap: 0, reachable: 0>

Turns out OkHttp 4 is not officially compatible with GraalVM.
Solution: OkHttpReflectionFeature.
Also tried to update GraalVM (Dockerfile) but this obviously didn't
solve the issue.
Still kept the change because
* we now have a supported base image and the latest version of JDK17
built in
* it makes the build faster simplifies the Dockerfile (no building musl
and zlib anymore 🥳)

Dockerfile

This made Integration Tests fail with
HttpHostConnectException: Connect to jenkins.localhost:80 [jenkins.localhost/127.0.0.1, jenkins.localhost/0:0:0:0:0:0:0:1] failed: Connection refused

Solution was to set the URL into every request sent by the ITs
explicitly.
As it was already done for the namespace Job.
Otherwise, the jobs will all use the host "jenkins.localhost" which does
 not work in other container (only on the host).

ALso make ITs more flexible: They should now run on all OSes using
ingress and using NodePort and k3d node IP in our Jenkins build.