Run native-image-agent multiple times.
With different params. Hopefully avoids Exception when --jenkins-url param is added.

groovy.lang.GroovyRuntimeException: Failed to create DGM method proxy : java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$1154
10:11:05  	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:106)
10:11:05  	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:93)
10:11:05  	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:78)
10:11:05  	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3272)
10:11:05  	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3264)
10:11:05  	at groovy.lang.MetaClassImpl.getNormalMethodWithCaching(MetaClassImpl.java:1460)
10:11:05  	at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1376)
10:11:05  	at groovy.lang.MetaClassImpl.getMetaMethod(MetaClassImpl.java:1280)
10:11:05  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1132)
10:11:05  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
10:11:05  	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1017)
10:11:05  	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1008)
10:11:05  	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToBoolean(DefaultTypeTransformation.java:197)
10:11:05  	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.booleanUnbox(DefaultTypeTransformation.java:86)
10:11:05  	at com.cloudogu.gitops.core.ApplicationConfigurator.addInternalStatus(ApplicationConfigurator.groovy:45)
10:11:05  	at com.cloudogu.gitops.core.ApplicationConfigurator.populateConfig(ApplicationConfigurator.groovy:32)
10:11:05  	at com.cloudogu.gitops.cli.GitopsPlaygroundCli.run(GitopsPlaygroundCli.groovy:112)