Update Jenkins
Suddenly this exception leads Jenkins to no longer start

SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Credentials Binding Plugin v681.vf91669a_32e45 (credentials-binding)
java.io.IOException: Failed to load: Credentials Binding Plugin (credentials-binding 681.vf91669a_32e45)
 - Update required: SSH Credentials Plugin (ssh-credentials 322.v124df57ed808) to be updated to 337.v395d2403ccd4 or higher