apply-ng: simplify getRootDir()
Jenkins build failed, because there the user.dir was "tmp/workspace/u-github_gitops-playground_..." which resulted in getRootDir() returning null implicitly and then

Setting internal scmm configs
java.io.FileNotFoundException: null/scm-manager/values.yaml (No such file or directory)

This whole logic should never be needed anyway, so just remove it.